-- AlterTable
ALTER TABLE "Bubble" ADD COLUMN "color" TEXT NOT NULL DEFAULT '#111111';
ALTER TABLE "Bubble" ADD COLUMN "fontSize" INTEGER NOT NULL DEFAULT 14;
ALTER TABLE "Bubble" ADD COLUMN "bold" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Bubble" ADD COLUMN "rotation" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Bubble" ADD COLUMN "zIndex" INTEGER NOT NULL DEFAULT 0;
